builds:
  archon:
    name: Archon
    gearSetup: default
    talents:
      composite:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3299882250886639_IN_IV
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjxyMDzsNzwMsNzMmZmxGyMWMTDwMAzsZGNbGAyYsAgZAGzMzY2GzstMAzgB
      dungeons:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_1_Mis_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMmZWmZYmx2MGzMzYDZGLmpBYGgZ2MDzmBgMGLAYGIjZmZMbjZ2WGgZiB
      single:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3299882250886639_IN_IV
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjxyMDzsNzwMsNzMmZmxGyMWMTDwMAzsZGNbGAyYsAgZAGzMzY2GzstMAzgB
      2t:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3299881948929519_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMMz2MDzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZAjZmZMbjZ2WGgZwA
      3t:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3299882093533679_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMmZ2mZYG2mZGzMzYDZGLmpBYGgZ2MjmNDAZMWAAMYMzMjZbMz2yAMDGA
      8t:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3299882076757487_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZAAAAAAAAAAAAMMLmxYZmxMz2MDzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAGMYMzMjZbMz2yAMDGA
  voidweaver:
    gearSetup: default
    name: Voidweaver
    talents:
      composite:
        name: VW_DH_VF_nzoth_yogg_cthun_3299882057915887_IN_IV
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghhZMWmZYmtZGmhtZmxMzM2QmxiZaAmZmBACwsNbLBzGDwYMYMzMjZbMDmZwMYA
      dungeons:
        name: VW_DH_VF_nzoth_yogg_cthun_1_Mis_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMmZWmZYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYkxMzMmtxMYmBzED
      single:
        name: VW_DH_VF_nzoth_yogg_cthun_3299882250395119_IN_IV
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxgZMWmZYmtZGmhtZmxMzM2QmxiZaAmZmBACwsNbLBzGDwMDYMzMjZbMDmZwMYA
      2t:
        name: VW_DH_VF_nzoth_yogg_cthun_3299882093533679_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMmZ2mZYG2mZGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmtxMYmBzgB
      3t:
        name: VW_DH_VF_yshaarj_nzoth_yogg_4127135744416239_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMjZMGAAAAAAAAAAAAjZZmxYZmxMz2MDzw2MzYmZGbIzYxMNAzMzAABY2mtlgZjBAGMmZmxsNmBzMYGMA
      8t:
        name: VW_DH_VF_nzoth_yogg_cthun_3299882093533679_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMmZ2mZYG2mZGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmtxMYmBzgB
hero:
  AR:
    AR_EC_RP: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/energy_compression:1/resonant_energy:1/energy_cycle:1/realized_potential:1/divine_halo:1"
    AR_EC_SW: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/energy_compression:1/resonant_energy:1/energy_cycle:1/spiritwell:1/divine_halo:1"
    AR_SP_RP: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/sustained_potency:1/resonant_energy:1/energy_cycle:1/realized_potential:1/divine_halo:1"
    AR_SP_SW: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/sustained_potency:1/resonant_energy:1/energy_cycle:1/spiritwell:1/divine_halo:1"
  VW:
    VW_VE: "void_torrent:1/dark_energy:1/void_blast:1/inner_quietus:1/voidheart:1/devour_matter:1/void_empowerment:1/voidwraith:1/touch_of_the_void:1/quickened_pulse:1/void_infusion:1/void_leech:1/overwhelming_shadows:1/collapsing_void:1"
    VW_DH: "void_torrent:1/dark_energy:1/void_blast:1/inner_quietus:1/voidheart:1/devour_matter:1/darkening_horizon:1/voidwraith:1/touch_of_the_void:1/quickened_pulse:1/void_infusion:1/void_leech:1/overwhelming_shadows:1/collapsing_void:1"
gear:
  # 14.88% Mastery | 36.22% Haste | 15.02% Crit | 4.96% Vers (Raid-Buffed)
  default:
    head: "blind_oaths_winged_crest,id=250051,ilevel=289" # haste/crit
    neck: "eternal_voidsong_chain,id=249368,ilevel=289" # haste/mastery
    shoulders: "blind_oaths_seraphguards,id=250049,ilevel=289" # crit/mastery
    back: "draconic_nullcape,id=249370,ilevel=289" # haste/mastery
    chest: "blind_oaths_raiment,id=250054,ilevel=289" # mastery/haste
    wrists: "martyrs_bindings,id=239648,ilevel=285,bonus_id=8793/12384" # haste/mastery 
    hands: "vilehex_bonds,id=251172,ilevel=289" # crit/haste
    waist: "arcanoweave_cord,id=239664,ilevel=285" # haste/crit
    legs: "blind_oaths_leggings,id=250050,ilevel=289" # haste/mastery
    feet: "lightbinder_treads,id=109796,ilevel=289" # haste/mastery
    finger1: "omission_of_light,id=251093,ilevel=289" # haste/mastery
    finger2: "occlusion_of_void,id=251217,ilevel=289" # haste
    trinket1: "vaelgors_final_stare,id=249346,ilevel=298"
    trinket2: "gaze_of_the_alnseer,id=249343,ilevel=298"
    main_hand: "belomelorn_the_shattered_talon,id=249283,ilevel=298" # haste/mastery
    off_hand: "tome_of_alnscorned_regret,id=249922,ilevel=298" # haste/mastery
  # x Mastery | x Haste | x Crit | x Vers
  noCantrip:
    head: "blind_oaths_winged_crest,id=250051,ilevel=289" # haste/crit
    neck: "amulet_of_the_abyssal_hymn,id=250247,ilevel=289" # mastery/haste
    shoulders: "blind_oaths_seraphguards,id=250049,ilevel=289" # crit/mastery
    back: "draconic_nullcape,id=249370,ilevel=289" # haste/mastery
    chest: "blind_oaths_raiment,id=250054,ilevel=289" # mastery/haste
    wrists: "voracious_wristwraps,id=249315,ilevel=289" # haste/mastery 
    hands: "vilehex_bonds,id=251172,ilevel=289" # crit/haste
    waist: "endless_march_waistwrap,id=249319,ilevel=289" # haste/crit
    legs: "blind_oaths_leggings,id=250050,ilevel=289" # haste/mastery
    feet: "lightbinder_treads,id=109796,ilevel=289" # haste/mastery
    finger1: "omission_of_light,id=251093,ilevel=289" # haste/mastery
    finger2: "eye_of_midnight,id=249920,ilevel=289" # haste
    trinket1: "shadow_of_the_empyrean_requiem,id=249810,ilevel=298"
    trinket2: "vaelgors_final_stare,id=249346,ilevel=298"
    main_hand: "belomelorn_the_shattered_talon,id=249283,ilevel=298" # haste/mastery
    off_hand: "tome_of_alnscorned_regret,id=249922,ilevel=298" # haste/mastery
gems:
  meta: "240983" # Indecipherable_Eversong_Diamond_2
  main: "240900" # Flawless Quick Amethyst
  peridot: "240892" # Flawless Masterful Peridot
  garnet: "240908" # Flawless Masterful Garnet
  amethyst: "240900" # Flawless Quick Amethyst
  lapis: "240918" # Flawless Masterful Lapis
enchants:
  head: ""
  chest: "mark_of_the_worldsoul_2" # "mark_of_the_worldsoul_2"
  ring: "eyes_of_the_eagle_2" # "zuljins_mastery_2"
  legs: "sunfire_silk_spellthread_2" # "sunfire_silk_spellthread_2"
  main_hand: "acuity_of_the_rendorei_2" # "acuity_of_the_rendorei_2"
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character. Lists each consumable at ranks 1, 2, and 3."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only."
    gearOverride: none
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims Food and Augment Rune consumables you can use to augment your character."
    gearOverride: none
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot. Lists each enchant at ranks 1, 2, and 3."
    gearOverride: none
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
    files:
      - enchants.simc
  gems:
    description: "Sims all available gems against each other. Lists each gem at ranks 1, 2, and 3."
    gearOverride: none
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
    files:
      - gems.simc
  omnium-folio:
    description: "Sims the Omnium Folio against each other. Lists each rank of the Folio."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - folio.simc
  racials:
    description: "Swaps out the racial that includes all stat effects or special abilities where they prove to be a DPS increase."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  special-gear:
    description: "Sims unique gear with effects to see the DPS gain. Includes Tailoring, Jewelcrafting, and Inscription gear, crafted with BiS stats when possible. Compared against Mythic BiS gear from the Raid or Mythic+ gear.<br><br>A negative DPS gain means the crafted piece with BiS stats is worse than the Mythic BiS piece. This usually means the BiS piece has a higher ilvl than the crafted piece."
    gearOverride: noCantrip
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - gear.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 1000 stat each step)."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims various talent builds generated by Talent Tree Manager. Shows the major cooldown and Idol combination used for that actor, names in gold can be clicked to copy the import string."
    gearOverride: none
    iterations: smart
    builds: false
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - DA-Spike.simc
      - DA-Flay.simc
      - DA-Spike_DR.simc
      - DA-Flay_DR.simc
      - VF-Spike.simc
      - VF-Flay.simc
      - VF-Spike_DR.simc
      - VF-Flay_DR.simc
  talents-top:
    description: "Shows top talents."
    gearOverride: none
    iterations: 20000
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - talents.simc
  tiersets:
    description: "Sims each tier set currently available by just activating just the set effect, not with the gear."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: "Combines the top trinkets together to get your BiS 2 trinkets."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 285
      - 298
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for current BiS gear setup..
    gearOverride: none
    builds: true
    weights: true
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsRaidSeasonOne
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
threeTargetWeights: weightsThreeTargets
fourTargetWeights: weightsFourTargets
eightTargetWeights: weightsEightTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
councilTargets: 3
dungeonSeason: 1
dungeonStandardWeights: weightsSeasonOne
dungeonPushWeights: weightsSeasonOne
dungeonType: route
simcBuild: latest
forceHeroTalents: false
defaultIterations: 10000
raidbots:
  apiUrlBase: https://mimiron.raidbots.com
  numOfRetries: 100
  retryInterval: 10
charts:
  wowheadUrl: https://www.wowhead.com/ptr-2/
analyze:
  dungeonCharts: false
  markdown: true
  csv: true
  json: true
stats:
  base: 400
  steps: 100
  total: 2400
  min:
    haste: 400
    mastery: 400
    crit: 0
    vers: 0
  max:
    haste: 1600
    mastery: 1600
    crit: 1600
    vers: 1000
  include:
    - mastery
    - haste
    - crit
    - versatility
talents:
  choice_pairs:
    - keywords: [misery, invoked_nightmare]
      suffixes: [Mis, IN]
    - keywords: [improved_voidform, ancient_madness]
      suffixes: [IV, AM]
    - keywords: [distorted_reality, minds_eye]
      suffixes: [DR, ME]
    - keywords: [deathspeaker, death_and_madness]
      suffixes: [DS, DaM]
  choice_singletons:
    - keyword: voidtouched
      suffix: VT
  idols:
    - yshaarj
    - nzoth
    - yogg
    - cthun