builds:
  archon:
    name: Archon
    gearSetup: default
    talents:
      composite:
        name: AR_SP_SW_VF_nzoth_yogg_3078143631544303_IN_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZAjZmZMbMz2yAMDGA
      dungeons:
        name: AR_SP_SW_VF_nzoth_yogg_3078143631544303_Mis_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZAjZmZMbMz2yAMDGA
      single:
        name: AR_SP_SW_VF_nzoth_yogg_3078143631544303_IN_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZAjZmZMbMz2yAMDGA
      2t:
        name: AR_SP_SW_VF_nzoth_yogg_3078143665065967_IN_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMDzAAAAAAAAAAAAwMLmxMbzMmZ2mxYG2mZGzMzYDZGLmpBYGgZ2MjmNDAZMWAwMAjZmZMbMz2yAMDGA
      3t:
        name: AR_SP_SW_VF_nzoth_yogg_3078143631544303_IN_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZAjZmZMbMz2yAMDGA
      8t:
        name: AR_SP_SW_VF_nzoth_yogg_3078143631544303_IN_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZAjZmZMbMz2yAMDGA
  voidweaver:
    gearSetup: default
    name: Voidweaver
    talents:
      composite:
        name: VW_DH_VF_nzoth_yogg_3078143852960751_IN_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAAMLmxMbzMMz2MzYG2mZGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmtxMYmBzgB
      dungeons:
        name: VW_DH_VF_nzoth_yogg_3078143966993391_Mis_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMzYG2mZGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmNmBzMYGMA
      single:
        name: VW_DH_VF_nzoth_yogg_3078143852960751_IN_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAAMLmxMbzMMz2MzYG2mZGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmtxMYmBzgB
      2t:
        name: VW_DH_VF_nzoth_yogg_3078143852960751_IN_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAAMLmxMbzMMz2MzYG2mZGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmtxMYmBzgB
      3t:
        name: VW_DH_VF_nzoth_yogg_3078143820454895_IN_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZAAAAAAAAAAAAgZxMmZbmxMz2MzYG2mZGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmtxMYmBzgB
      8t:
        name: VW_DH_VF_nzoth_yogg_3078143820454895_IN_AM_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZAAAAAAAAAAAAgZxMmZbmxMz2MzYG2mZGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmtxMYmBzgB
hero:
  AR:
    AR_EC_RP: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/energy_compression:1/resonant_energy:1/energy_cycle:1/realized_potential:1/divine_halo:1"
    AR_EC_SW: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/energy_compression:1/resonant_energy:1/energy_cycle:1/spiritwell:1/divine_halo:1"
    AR_SP_RP: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/sustained_potency:1/resonant_energy:1/energy_cycle:1/realized_potential:1/divine_halo:1"
    AR_SP_SW: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/sustained_potency:1/resonant_energy:1/energy_cycle:1/spiritwell:1/divine_halo:1"
  VW:
    VW_VE: "void_torrent:1/dark_energy:1/void_blast:1/inner_quietus:1/voidheart:1/devour_matter:1/void_empowerment:1/voidwraith:1/touch_of_the_void:1/quickened_pulse:1/void_infusion:1/void_leech:1/overwhelming_shadows:1/collapsing_void:1"
    VW_DH: "void_torrent:1/dark_energy:1/void_blast:1/inner_quietus:1/voidheart:1/devour_matter:1/darkening_horizon:1/voidwraith:1/touch_of_the_void:1/quickened_pulse:1/void_infusion:1/void_leech:1/overwhelming_shadows:1/collapsing_void:1"
gear:
  # 14.88% Mastery | 36.22% Haste | 15.02% Crit | 4.96% Vers (Raid-Buffed)
  default:
    head: "cosmic_penitents_truesight,id=271555,bonus_id=13846,ilevel=344" # mastery
    neck: "aqirbane_reliquary,id=268265,bonus_id=13708,ilevel=344" # crit
    shoulders: "cosmic_penitents_echoing_screams,id=271553,ilevel=334" # crit/haste
    back: "silken_voodoo_drape,id=268253,ilevel=344" # mastery/haste
    chest: "cosmic_penitents_eclipsing_robes,id=271558,ilevel=344" # mastery/crit
    wrists: "martyrs_bindings,id=239648,ilevel=331,bonus_id=8793/12384" # haste/mastery 
    hands: "cosmic_penitents_celestial_grips,id=271556,ilevel=344" # haste/mastery
    waist: "arcanoweave_cord,id=239664,ilevel=331" # haste/crit
    legs: "enveloping_legwraps_of_the_cosmic_penitent,id=271554,ilevel=334" # haste/crit
    feet: "cackling_soultreads,id=268255,ilevel=344" # haste/mastery
    finger1: "sickening_signet_of_atroxus,id=252258,ilevel=334" # haste/mastery
    finger2: "vile_alchemists_band,id=268249,ilevel=334" # mastery/crit
    trinket1: "gebbos_bottomless_bag,id=270164,ilevel=334"
    trinket2: "freightrunners_flask,id=250215,ilevel=334"
    main_hand: "janthrazet_the_soul_fang,id=271092,ilevel=344" # haste
    off_hand: "spine_of_the_hissing_abyss,id=268197,ilevel=334" # mastery/haste
  # x Mastery | x Haste | x Crit | x Vers
  noCantrip:
    head: "errant_scrollsages_hood,id=268242,ilevel=334" # haste/crit
    neck: "amulet_of_the_twin_fangs,id=268251,ilevel=334" # crit
    shoulders: "cosmic_penitents_echoing_screams,id=271553,ilevel=334" # crit/haste
    back: "silken_voodoo_drape,id=268253,ilevel=334" # mastery/haste
    chest: "cosmic_penitents_eclipsing_robes,id=271558,ilevel=334" # mastery/crit
    wrists: "venomsinged_cuffs,id=268228,ilevel=334" # mastery/crit 
    hands: "cosmic_penitents_celestial_grips,id=271556,ilevel=334" # haste/mastery
    waist: "endless_march_waistwrap,id=249319,ilevel=334" # haste/crit
    legs: "enveloping_legwraps_of_the_cosmic_penitent,id=271554,ilevel=334" # haste/crit
    feet: "cackling_soultreads,id=268255,ilevel=334" # haste/mastery
    finger1: "sickening_signet_of_atroxus,id=252258,ilevel=334" # haste/mastery
    finger2: "vile_alchemists_band,id=268249,ilevel=334" # mastery/crit
    trinket1: "gebbos_bottomless_bag,id=270164,ilevel=334"
    trinket2: "freightrunners_flask,id=250215,ilevel=334"
    main_hand: "hexing_spiritrender,id=268203,ilevel=334" # haste/mastery
    off_hand: "spine_of_the_hissing_abyss,id=268197,ilevel=334" # mastery/haste
gems:
  meta: "240983" # Indecipherable_Eversong_Diamond_2
  main: "240900" # Flawless Quick Amethyst
  peridot: "240892" # Flawless Masterful Peridot
  garnet: "240908" # Flawless Masterful Garnet
  amethyst: "240900" # Flawless Quick Amethyst
  lapis: "240918" # Flawless Masterful Lapis
enchants:
  head: ""
  chest: "mark_of_the_worldsoul_2" # "mark_of_the_worldsoul_2"
  ring: "eyes_of_the_eagle_2" # "zuljins_mastery_2"
  legs: "sunfire_silk_spellthread_2" # "sunfire_silk_spellthread_2"
  main_hand: "acuity_of_the_rendorei_2" # "acuity_of_the_rendorei_2"
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character. Lists each consumable at ranks 1, 2, and 3."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only."
    gearOverride: none
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims Food and Augment Rune consumables you can use to augment your character."
    gearOverride: none
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot. Lists each enchant at ranks 1, 2, and 3."
    gearOverride: none
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
    files:
      - enchants.simc
  gems:
    description: "Sims all available gems against each other. Lists each gem at ranks 1, 2, and 3."
    gearOverride: none
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
    files:
      - gems.simc
  omnium-folio:
    description: "Sims the Omnium Folio against each other. Lists each rank of the Folio."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - folio.simc
  racials:
    description: "Swaps out the racial that includes all stat effects or special abilities where they prove to be a DPS increase."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  special-gear:
    description: "Sims unique gear with effects to see the DPS gain. Includes Tailoring, Jewelcrafting, and Inscription gear, crafted with BiS stats when possible. Compared against Mythic BiS gear from the Raid or Mythic+ gear.<br><br>A negative DPS gain means the crafted piece with BiS stats is worse than the Mythic BiS piece. This usually means the BiS piece has a higher ilvl than the crafted piece."
    gearOverride: noCantrip
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - gear.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 200 stat each step)."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims various talent builds generated by Talent Tree Manager. Shows the major cooldown and Idol combination used for that actor, names in gold can be clicked to copy the import string."
    gearOverride: none
    iterations: smart
    builds: false
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - DA-Spike.simc
      - DA-Flay.simc
      - DA-Spike_DR.simc
      - DA-Flay_DR.simc
      - VF-Spike.simc
      - VF-Flay.simc
      - VF-Spike_DR.simc
      - VF-Flay_DR.simc
  talents-top:
    description: "Shows top talents."
    gearOverride: none
    iterations: 20000
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - talents.simc
  tiersets:
    description: "Sims each tier set currently available by just activating just the set effect, not with the gear."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: "Combines the top trinkets together to get your BiS 2 trinkets."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: item
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for current BiS gear setup..
    gearOverride: none
    builds: true
    weights: true
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsRaidSeasonOne
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
threeTargetWeights: weightsThreeTargets
fourTargetWeights: weightsFourTargets
eightTargetWeights: weightsEightTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
councilTargets: 3
dungeonSeason: 1
dungeonStandardWeights: weightsSeasonOne
dungeonPushWeights: weightsSeasonOne
dungeonType: slice
simcBuild: latest
forceHeroTalents: false
defaultIterations: 10000
raidbots:
  apiUrlBase: https://mimiron.raidbots.com
  numOfRetries: 100
  retryInterval: 10
charts:
  wowheadUrl: https://www.wowhead.com/ptr/
analyze:
  dungeonCharts: false
  markdown: true
  csv: true
  json: true
stats:
  base: 800
  steps: 200
  total: 3200
  min:
    haste: 800
    mastery: 800
    crit: 200
    vers: 200
  max:
    haste: 2000
    mastery: 2000
    crit: 1400
    vers: 400
  include:
    - mastery
    - haste
    - crit
    - versatility
talents:
  choice_pairs:
    - keywords: [misery, invoked_nightmare]
      suffixes: [Mis, IN]
    - keywords: [improved_voidform, ancient_madness]
      suffixes: [IV, AM]
    - keywords: [distorted_reality, minds_eye]
      suffixes: [DR, ME]
    - keywords: [deathspeaker, death_and_madness]
      suffixes: [DS, DaM]
  choice_singletons:
    - keyword: voidtouched
      suffix: VT
  idols:
    - yshaarj
    - nzoth
    - yogg
    - cthun