builds:
  archon:
    name: Archon
    gearSetup: default
    talents:
      composite:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3299881948929519_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMMz2MDzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZQGzMzY2GzgtlBAzMzE
      dungeons:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3299881948929519_Mis_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMMzyMDzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZQGzMzY2GzgtlBAzMzE
      single:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3299881948930029_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMY2mZGzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZQGzMzY2GzgtlBAzMzE
      2t:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3299881948929519_IN_IV_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZzMGLzMMz2MDzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZQGzMzY2GzgtlBAzMzE
      3t:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3299881948929519_IN_IV_DR
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZzMGLzMMz2MDzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZQGzMzY2GzgtlBAzMzE
      8t:
        name: AR_SP_SW_VF_nzoth_yogg_cthun_3282427344379375_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjxAAAAAAAAAAAAMMLmxMLzMMz2MDzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAGjRGzMzY2GzgtlBAzMzE
  voidweaver:
    gearSetup: default
    name: Voidweaver
    talents:
      composite:
        name: VW_DH_VF_nzoth_yogg_cthun_3299881948929519_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMMz2MDzw2MzYmZGbIzYxMNAzMzAABY2mtlgZjBYmBZMzMjZbMDwMDwMzMB
      dungeons:
        name: VW_DH_VF_nzoth_yogg_cthun_3299882091444719_Mis_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMMzyMDzw2MzYmZGbIzYxMNAzMzAABY2mtlgZjBAzIjZmZMbjZAmZAmZmJA
      single:
        name: VW_DH_VF_nzoth_yogg_cthun_3299881948930029_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAghZxMGLzMY2mZGzw2MzYmZGbIzYxMNAzMzAABY2mtlgZjBYmBZMzMjZbMDwMDwMzMB
      2t:
        name: VW_DH_VF_nzoth_yogg_cthun_3282428420184559_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjxAAAAAAAAAAAAMMLmxMLzMmZ2mZYG2mZGzMzYDZGLmpBYmZGAIAz2stEMbMAwMZMzMjZbMDwMDwMzMB
      3t:
        name: VW_DH_VF_nzoth_yogg_cthun_3282428420184559_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMMjxAAAAAAAAAAAAMMLmxMLzMmZ2mZYG2mZGzMzYDZGLmpBYmZGAIAz2stEMbMAwMZMzMjZbMDwMDwMzMB
      8t:
        name: VW_DH_VF_yshaarj_nzoth_yogg_4127135744416239_IN_IV_ME
        string: CIQAAAAAAAAAAAAAAAAAAAAAAMjZMGAAAAAAAAAAAAjZZmxYZmxMz2MDzw2MzYmZGbIzYxMNAzMzAABY2mtlgZjBAGZMzMjZbMDwMDwMzMB
hero:
  AR:
    AR_EC_RP: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/energy_compression:1/resonant_energy:1/energy_cycle:1/realized_potential:1/divine_halo:1"
    AR_EC_SW: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/energy_compression:1/resonant_energy:1/energy_cycle:1/spiritwell:1/divine_halo:1"
    AR_SP_RP: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/sustained_potency:1/resonant_energy:1/energy_cycle:1/realized_potential:1/divine_halo:1"
    AR_SP_SW: "halo:1/perfected_form:1/power_surge:1/manifested_power:1/focused_outburst:1/incessant_screams:1/energy_conservation:1/empowered_surges:1/word_of_supremacy:1/sustained_potency:1/resonant_energy:1/energy_cycle:1/spiritwell:1/divine_halo:1"
  VW:
    VW_VE: "void_torrent:1/dark_energy:1/void_blast:1/inner_quietus:1/voidheart:1/devour_matter:1/void_empowerment:1/voidwraith:1/touch_of_the_void:1/quickened_pulse:1/void_infusion:1/void_leech:1/overwhelming_shadows:1/collapsing_void:1"
    VW_DH: "void_torrent:1/dark_energy:1/void_blast:1/inner_quietus:1/voidheart:1/devour_matter:1/darkening_horizon:1/voidwraith:1/touch_of_the_void:1/quickened_pulse:1/void_infusion:1/void_leech:1/overwhelming_shadows:1/collapsing_void:1"
gear:
  # x Mastery | x Haste | x Crit | x Vers
  default:
    head: "12.0_raid__class_set__priest__armor__cloth___head,id=250051,ilevel=276" # haste/crit
    neck: "eternal_voidsong_chain,id=249368,ilevel=276" # 
    shoulders: "12.0_raid__class_set__priest__armor__cloth___shoulder,id=250049,ilevel=276" # crit/mastery
    back: "12.0_raid__generic__cloak,id=249370,ilevel=276" # 
    chest: "12.0_raid__class_set__priest__armor__cloth__robe,id=250054,ilevel=276" # mastery/haste
    wrists: "12.0_raid__cloth__wrist,id=249315,ilevel=276" # 
    hands: "item__cloth__hand,id=251172,ilevel=276" # 
    waist: "12.0_raid__cloth__waist,id=249319,ilevel=276" # 
    legs: "12.0_raid__class_set__priest__armor__cloth___legs,id=250050,ilevel=276" # haste/mastery
    feet: "lightbinder_treads,id=109796,ilevel=276" # haste/mastery
    finger1: "omission_of_light,id=251093,ilevel=276" # haste/mastery
    finger2: "eye_of_midnight,id=249920,ilevel=276" # 
    trinket1: "placeholder1,id=153860,ilevel=276"
    trinket2: "placeholder2,id=153864,ilevel=276"
    main_hand: "12.0_raid__dagger__int__boss_name__weapon,id=249283,ilevel=276" # 
    off_hand: "12.0_raid__generic__holdable,id=249922,ilevel=276" #
  # x Mastery | x Haste | x Crit | x Vers
  noCantrip:
    head: "12.0_raid__class_set__priest__armor__cloth___head,id=250051,ilevel=276" # haste/crit
    neck: "eternal_voidsong_chain,id=249368,ilevel=276" # 
    shoulders: "12.0_raid__class_set__priest__armor__cloth___shoulder,id=250049,ilevel=276" # crit/mastery
    back: "12.0_raid__generic__cloak,id=249370,ilevel=276" # 
    chest: "12.0_raid__class_set__priest__armor__cloth__robe,id=250054,ilevel=276" # mastery/haste
    wrists: "12.0_raid__cloth__wrist,id=249315,ilevel=276" # 
    hands: "item__cloth__hand,id=251172,ilevel=276" # 
    waist: "12.0_raid__cloth__waist,id=249319,ilevel=276" # 
    legs: "12.0_raid__class_set__priest__armor__cloth___legs,id=250050,ilevel=276" # haste/mastery
    feet: "lightbinder_treads,id=109796,ilevel=276" # haste/mastery
    finger1: "omission_of_light,id=251093,ilevel=276" # haste/mastery
    finger2: "eye_of_midnight,id=249920,ilevel=276" # 
    trinket1: "placeholder1,id=153860,ilevel=276"
    trinket2: "placeholder2,id=153864,ilevel=276"
    main_hand: "12.0_raid__dagger__int__boss_name__weapon,id=249283,ilevel=276" # 
    off_hand: "12.0_raid__generic__holdable,id=249922,ilevel=276" #
gems:
  meta: "" # Powerful Eversong Diamond 240967
  main: "" # Flawless Quick Amethyst 240900
  peridot: "" # Flawless Masterful Peridot 240891
  garnet: "" # Flawless Masterful Garnet 240908
  amethyst: "" # Flawless Quick Amethyst 213497
  lapis: "" # Flawless Masterful Lapis 240918
enchants:
  head: ""
  chest: "" # mark_of_the_worldsoul_2
  ring: "" # zuljins_mastery_2
  legs: "" # sunfire_silk_spellthread_2
  main_hand: "" # acuity_of_the_rendorei_2
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character. Lists each consumable at ranks 1, 2, and 3."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only."
    gearOverride: none
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims Food and Augment Rune consumables you can use to augment your character."
    gearOverride: none
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot. Lists each enchant at ranks 1, 2, and 3."
    gearOverride: none
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - enchants.simc
  gem-combos:
    description: "Sims combinations of gems to optimize the meta gems using 1 of each color. Only uses max rank of gems"
    gearOverride: none
    iterations: 20000
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  gems:
    description: "Sims all available gems against each other. Lists each gem at ranks 1, 2, and 3."
    gearOverride: none
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - gems.simc
  racials:
    description: "Swaps out the racial that includes all stat effects or special abilities where they prove to be a DPS increase."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  special-gear:
    description: "Sims unique gear with effects to see the DPS gain. Includes Tailoring, Jewelcrafting, and Inscription gear, crafted with BiS stats when possible. Compared against Mythic BiS gear from the Raid or Mythic+ gear.<br><br>A negative DPS gain means the crafted piece with BiS stats is worse than the Mythic BiS piece. This usually means the BiS piece has a higher ilvl than the crafted piece."
    gearOverride: noCantrip
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - gear.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 1000 stat each step)."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims various talent builds generated by Talent Tree Manager. Shows the major cooldown and Idol combination used for that actor, names in gold can be clicked to copy the import string."
    gearOverride: none
    iterations: smart
    builds: false
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - DA-Spike.simc
      - DA-Flay.simc
      - DA-Spike_DR.simc
      - DA-Flay_DR.simc
      - VF-Spike.simc
      - VF-Flay.simc
      - VF-Spike_DR.simc
      - VF-Flay_DR.simc
  talents-top:
    description: "Shows top talents."
    gearOverride: none
    iterations: 20000
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - talents.simc
  tiersets:
    description: "Sims each tier set currently available by just activating just the set effect, not with the gear."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: "Combines the top trinkets together to get your BiS 2 trinkets."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    gearOverride: none
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 684
      - 697
      - 710
      - 717
      - 730
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for current BiS gear setup..
    gearOverride: none
    builds: true
    weights: true
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsLiberationofUndermine
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
threeTargetWeights: weightsThreeTargets
fourTargetWeights: weightsFourTargets
eightTargetWeights: weightsEightTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
councilTargets: 3
dungeonSeason: 2
dungeonStandardWeights: weightsSeasonTwo
dungeonPushWeights: weightsSeasonTwo
dungeonType: slice
simcBuild: latest
forceHeroTalents: false
defaultIterations: 10000
raidbots:
  apiUrlBase: https://mimiron.raidbots.com
  numOfRetries: 100
  retryInterval: 10
charts:
  wowheadUrl: https://www.wowhead.com/beta/
analyze:
  dungeonCharts: false
  markdown: true
  csv: true
  json: true
stats:
  base: 4000
  steps: 1500
  total: 58000
  min:
    haste: 8000
    mastery: 14000
    crit: 5000
    vers: 0
  max:
    haste: 30000
    mastery: 30000
    crit: 30000
    vers: 8500
  include:
    - mastery
    - haste
    - crit
    - versatility