#!/usr/bin/env python3
"""Generate simc trinket profile files from `trinkets.yml`.

Usage:
  python build_trinkets.py            # reads ./trinkets.yml and writes dungeons.simc, other.simc, raid.simc
  python build_trinkets.py --in-file path/to/trinkets.yml --out-dir outdir

The script produces simple `profileset` lines like:
  profileset."Name_717"+=trinket1=name_lowercase,id=12345,ilevel=717

This intentionally keeps output minimal and similar to the examples in the repo.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from typing import Any

try:
    import yaml
except Exception:  # pragma: no cover - helpful error message
    print(
        "Missing dependency: pyyaml. Install with: pip install pyyaml", file=sys.stderr
    )
    raise


def normalize_trinket_name(name: str) -> str:
    """Produce a lowercase identifier for the `trinket1=` field.

    Keeps letters, numbers and underscores. Replaces other characters with underscores.
    """
    s = name.strip()
    # remove hyphens entirely (e.g. "Locus-Walkers_Ribbon" -> "locuswalkers_ribbon")
    s = s.replace("-", "")
    s = s.lower()
    s = re.sub(r"[^a-z0-9_]+", "_", s)
    s = re.sub(r"_+", "_", s)
    s = s.strip("_")
    return s


def resolve_item_levels(raw, item_levels_map: dict[str, Any]) -> list:
    """Resolve an item_levels field which may be a list or a string key into a list.

    If `raw` is a string, look it up in `item_levels_map`. If it's a list, return it.
    Otherwise return an empty list.
    """
    if raw is None:
        return []
    if isinstance(raw, list):
        return raw
    if isinstance(raw, str):
        return item_levels_map.get(raw, [])
    return []


def write_simc_for_section(
    section_name: str,
    section: dict[str, Any],
    out_path: str,
    item_levels_map: dict[str, Any],
    base_content: str | None = None,
) -> None:
    trinkets = section.get("trinkets", [])
    # section.item_levels can be a list or a string key referencing the top-level map
    section_item_levels = resolve_item_levels(
        section.get("item_levels", None), item_levels_map
    )

    if not trinkets:
        print(f'No trinkets for section "{section_name}", skipping.')
        return

    # write header, then base actor block (if any), then profile lines
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Generated by build_trinkets.py - do not edit by hand\n")
        f.write(f"# Section: {section_name}\n\n")

        if base_content:
            f.write(base_content)
            if not base_content.endswith("\n"):
                f.write("\n")
            f.write("\n")

        for tr in trinkets:
            tr_id = tr.get("id")
            tr_name = tr.get("name")
            if not tr_id or not tr_name:
                # skip malformed entries
                continue

            normalized = normalize_trinket_name(tr_name)
            # support either 'option' (singular) or 'options' (plural)
            opts = tr.get("option") or tr.get("options") or []
            # support 'bonus_ids' for appending bonus_id directly to trinket line
            bonus_ids = tr.get("bonus_ids") or []
            # Only fall back to section item levels when per-trinket item_levels is not provided.
            # This preserves explicit empty arrays (e.g. item_levels: []) as "skip this trinket".
            if "item_levels" in tr:
                tr_item_levels = resolve_item_levels(
                    tr.get("item_levels", None), item_levels_map
                )
            else:
                tr_item_levels = section_item_levels

            if bonus_ids:
                for bonus in bonus_ids:
                    bonus_name = bonus.get("name")
                    bonus_val = bonus.get("value")
                    if not bonus_name or bonus_val is None:
                        continue

                    for il in tr_item_levels:
                        label = f"{tr_name}_{bonus_name}_{il}"
                        line = f'profileset."{label}"+=trinket1={normalized},id={tr_id},ilevel={il},bonus_id={bonus_val}\n'
                        f.write(line)
            elif opts:
                for opt in opts:
                    opt_name = opt.get("name")
                    opt_val_key = opt.get("value")
                    if not opt_name or opt_val_key is None:
                        continue
                    opt_norm = normalize_trinket_name(opt_name)

                    for il in tr_item_levels:
                        label = f"{tr_name}_{opt_name}_{il}"
                        trinket_id = f"{normalized}_{opt_norm}"
                        line = f'profileset."{label}"+=trinket1={trinket_id},id={tr_id},ilevel={il}\n'
                        f.write(line)
                        # write one or more option assignment lines depending on the type of `value`
                        if isinstance(opt_val_key, list):
                            f.writelines(f'profileset."{label}"+={v}\n' for v in opt_val_key)
                        else:
                            f.write(f'profileset."{label}"+={opt_val_key}\n')
            else:
                for il in tr_item_levels:
                    label = f"{tr_name}_{il}"
                    line = f'profileset."{label}"+=trinket1={normalized},id={tr_id},ilevel={il}\n'
                    f.write(line)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate .simc trinket profile files from a YAML config."
    )
    p.add_argument(
        "--in-file",
        default="trinkets.yml",
        help="YAML input file (default: trinkets.yml)",
    )
    p.add_argument(
        "--out-dir",
        default=".",
        help="Directory to write the .simc files to (default: current dir)",
    )
    p.add_argument(
        "--base-file",
        default="base.simc",
        help="Path to base.simc to append (default: base.simc next to the YAML file)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated output to stdout instead of writing files",
    )

    args = p.parse_args(argv)

    if not os.path.isfile(args.in_file):
        print(f"Input file not found: {args.in_file}", file=sys.stderr)
        return 2

    with open(args.in_file, "r", encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh)

    # top-level item_levels map (optional). Keys are names, values are lists of ilevels
    item_levels_map: dict[str, Any] = (
        cfg.get("item_levels", {}) if isinstance(cfg, dict) else {}
    )

    # sections are top-level dict entries except the `item_levels` map
    sections = [
        (k, v) for k, v in cfg.items() if isinstance(v, dict) and k != "item_levels"
    ]

    outputs: dict[str, str] = {
        "dungeons": "dungeons.simc",
        "other": "other.simc",
        "raid": "raid.simc",
    }

    # determine base file path (relative to the YAML file's directory by default)
    base_file = args.base_file
    yaml_dir = os.path.dirname(os.path.abspath(args.in_file)) or "."
    if not os.path.isabs(base_file):
        base_path = os.path.join(yaml_dir, base_file)
    else:
        base_path = base_file

    base_content = None
    if os.path.isfile(base_path):
        with open(base_path, "r", encoding="utf-8") as bf:
            base_content = bf.read()

    for name, section in sections:
        out_file = outputs.get(name)
        if not out_file:
            # ignore unknown sections but warn
            print(f'Warning: unknown section "{name}" - skipping')
            continue

        out_path = os.path.join(args.out_dir, out_file)

        if args.dry_run:
            # print to stdout (base first, then profiles)
            print("#" * 40)
            print(f"# Section: {name}")
            print("#" * 40)

            if base_content:
                print(base_content)

            # generate same content as write_simc_for_section but to stdout
            trinkets = section.get("trinkets", [])
            section_item_levels = resolve_item_levels(
                section.get("item_levels", None), item_levels_map
            )
            for tr in trinkets:
                tr_id = tr.get("id")
                tr_name = tr.get("name")
                if not tr_id or not tr_name:
                    continue
                normalized = normalize_trinket_name(tr_name)
                opts = tr.get("option") or tr.get("options") or []
                bonus_ids = tr.get("bonus_ids") or []
                if "item_levels" in tr:
                    tr_item_levels = resolve_item_levels(
                        tr.get("item_levels", None), item_levels_map
                    )
                else:
                    tr_item_levels = section_item_levels

                if bonus_ids:
                    for bonus in bonus_ids:
                        bonus_name = bonus.get("name")
                        bonus_val = bonus.get("value")
                        if not bonus_name or bonus_val is None:
                            continue
                        for il in tr_item_levels:
                            label = f"{tr_name}_{bonus_name}_{il}"
                            line = f'profileset."{label}"+=trinket1={normalized},id={tr_id},ilevel={il},bonus_id={bonus_val}'
                            print(line)
                elif opts:
                    for opt in opts:
                        opt_name = opt.get("name")
                        opt_val_key = opt.get("value")
                        if not opt_name or opt_val_key is None:
                            continue
                        opt_norm = normalize_trinket_name(opt_name)
                        for il in tr_item_levels:
                            label = f"{tr_name}_{opt_name}_{il}"
                            trinket_id = f"{normalized}_{opt_norm}"
                            line = f'profileset."{label}"+=trinket1={trinket_id},id={tr_id},ilevel={il}'
                            print(line)
                            # print one or more option assignment lines depending on the type of `value`
                            if isinstance(opt_val_key, list):
                                for v in opt_val_key:
                                    print(f'profileset."{label}"+={v}')
                            else:
                                print(f'profileset."{label}"+={opt_val_key}')
                else:
                    for il in tr_item_levels:
                        label = f"{tr_name}_{il}"
                        line = f'profileset."{label}"+=trinket1={normalized},id={tr_id},ilevel={il}'
                        print(line)

            print()
        else:
            # write profiles, with base content written before profiles if available
            write_simc_for_section(
                name, section, out_path, item_levels_map, base_content
            )
            print(f"Wrote {out_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
