import os
import importlib.util


def load_ttm_module(root_dir):
    ttm_path = os.path.join(root_dir, "talents/ttm.py")
    # ttm.py opens ../config.yml relative to the current working directory at import
    talents_dir = os.path.join(root_dir, "talents")
    os.makedirs(talents_dir, exist_ok=True)
    orig_cwd = os.getcwd()
    try:
        os.chdir(talents_dir)
        # ensure a minimal config.yml exists one level up
        config_path = os.path.join(root_dir, "config.yml")
        if not os.path.exists(config_path):
            with open(config_path, "w", encoding="utf8") as cf:
                cf.write("hero:\n  AR: {}\n  VW: {}\n")
        spec = importlib.util.spec_from_file_location("ttm", ttm_path)
        ttm = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(ttm)
    finally:
        os.chdir(orig_cwd)
    return ttm


def test_generate_suffix_and_talents_class(tmp_path):
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    ttm = load_ttm_module(root_dir)
    assert ttm.generate_suffix(["A", "B"]) == "A_B"
    # empty
    assert ttm.generate_suffix([]) == ""
    # Talents class
    t = ttm.Talents("a", "b", "c")
    assert t.st == "a" and t.ct == "b" and t.ht == "c"


def test_apply_rules_various_cases():
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    ttm = load_ttm_module(root_dir)
    # tormented_spirits without idol_of_yoggsaron -> should be filtered
    assert ttm.apply_rules("some foo tormented_spirits bar") is True

    # half-selected mid talents
    line = "instilled_doubt:1 something mastermind:1"
    assert ttm.apply_rules(line) is True

    # too few bottom talents -> filtered
    assert ttm.apply_rules("mindbender:1") is True

    # enough bottom talents -> not filtered
    many = " ".join([f"{t}:1" for t in [
        "mindbender",
        "deathspeaker",
        "death_and_madness",
        "mind_devourer",
        "auspicious_spirits",
        "inescapable_torment",
        "deaths_torment",
        "screams_of_the_void",
        "idol_of_cthun",
    ]])
    assert ttm.apply_rules(many) is False


def test_convert_builds_transforms_file(tmp_path, monkeypatch):
    # Work in the talents directory
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    monkeypatch.chdir(root_dir)
    ttm = load_ttm_module(root_dir)
    profile = tmp_path / "test_profile.simc"
    # craft a line that will be accepted (has 3 idols and >=9 bottom talents)
    idols = "idol_of_yshaarj idol_of_nzoth idol_of_yogg"
    bottoms = " ".join([f"{t}:1" for t in [
        "mindbender",
        "deathspeaker",
        "death_and_madness",
        "mind_devourer",
        "auspicious_spirits",
        "inescapable_torment",
        "deaths_torment",
        "screams_of_the_void",
        "idol_of_cthun",
    ]])
    # include choice nodes: invoked_nightmare, improved_voidform, minds_eye
    line = (
        f"Solved loadout voidform invoked_nightmare improved_voidform minds_eye {idols} {bottoms} 22111 profileset.\"VF\"+=\"SOME\"\n"
    )
    content = [line]
    (tmp_path / "dummy").mkdir(exist_ok=True)
    # write file in tmp dir and run conversion on that path
    with open(profile, "w", encoding="utf8") as f:
        f.writelines(content)

    ttm.convert_builds(str(profile))

    # verify signature and transformed content
    with open(profile, "r", encoding="utf8") as f:
        out = f.read()
    assert out.startswith("# Automatically generated by ttm.py\n")
    # Profileset key should have idols appended
    assert 'profileset."VF_yshaarj_nzoth_yogg' in out
    # numeric cluster replaced by suffix pieces (IN and IV and ME expected)
    assert "_IN_" in out and "_IV" in out and "_ME" in out


def test_duplicate_and_make_build_files(tmp_path, monkeypatch):
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    # load module (imports config relative to talents)
    ttm = load_ttm_module(root_dir)

    # Create hero files and base.simc inside tmp_path so tests do not pollute repo
    ar_file = tmp_path / "hero_AR.simc"
    vw_file = tmp_path / "hero_VW.simc"
    ar_file.write_text('profileset."T1"+="spec1 minds_eye _ME"\n', encoding="utf8")
    vw_file.write_text('profileset."T2"+="spec2"\n', encoding="utf8")

    # ensure base.simc exists in tmp_path
    base_file = tmp_path / "base.simc"
    base_file.write_text("BASELINE\n", encoding="utf8")

    # prepare builds dir in tmp_path and a stray file to be removed
    builds_dir = tmp_path / "builds"
    builds_dir.mkdir(exist_ok=True)
    (builds_dir / "old.simc").write_text("OLD\n", encoding="utf8")

    # monkeypatch config used by duplicate_builds
    ttm.config = {"hero": {"AR": {"HERO1": "hero_tal=1"}, "VW": {"VH1": "hero_v=1"}}}

    # change cwd to tmp_path so ttm writes its outputs there
    monkeypatch.chdir(str(tmp_path))

    # run duplication (writes hero_*_duplicated.simc into tmp_path)
    ttm.duplicate_builds()
    assert (tmp_path / "hero_AR_duplicated.simc").exists()
    assert (tmp_path / "hero_VW_duplicated.simc").exists()

    # run make_build_files
    ttm.make_build_files()
    # expect at least one batch file created in builds_dir
    files = [f.name for f in builds_dir.iterdir() if f.name.startswith("talents_")]
    assert len(files) >= 1
    # check that baseline was written into the first batch file
    with open(builds_dir / files[0], "r", encoding="utf8") as f:
        batch_content = f.read()
    assert "BASELINE" in batch_content


# Additional tests merged from test_ttm_more.py
def test_half_selected_bottom_talents_filters(tmp_path):
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    ttm = load_ttm_module(root)
    # two half-selected bottom talents (':1') should trigger filter
    line = "madness_weaving:1 screams_of_the_void:1"
    assert ttm.apply_rules(line) is True


def test_convert_builds_already_generated(tmp_path, monkeypatch, capsys):
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    monkeypatch.chdir(os.path.join(root, "talents"))
    ttm = load_ttm_module(root)
    profile = tmp_path / "already.simc"
    SIGNATURE = "# Automatically generated by ttm.py\n"
    with open(profile, "w", encoding="utf8") as f:
        f.write(SIGNATURE)
        f.write('some other line\n')

    # calling convert_builds should detect signature and return early
    ttm.convert_builds(str(profile))
    capsys.readouterr()
    # file should be unchanged (still start with signature)
    with open(profile, "r", encoding="utf8") as f:
        contents = f.read()
    assert contents.startswith(SIGNATURE)


def test_choice_nodes_and_idol_combination(tmp_path, monkeypatch):
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    monkeypatch.chdir(os.path.join(root, "talents"))
    ttm = load_ttm_module(root)

    profile = tmp_path / "choice.simc"
    # build a line that selects Mis (misery), AM, DR, DaM, VT and 3 idols
    idols = "idol_of_yshaarj idol_of_nzoth idol_of_yogg"
    bottoms = " ".join([f"{t}:1" for t in [
        "mindbender",
        # omit deathspeaker so death_and_madness => DaM
        "death_and_madness",
        "mind_devourer",
        "auspicious_spirits",
        "inescapable_torment",
        "deaths_torment",
        "screams_of_the_void",
        "idol_of_cthun",
    ]])
    # use madness_weaving:2 to avoid half-selected bottom filter
    bottoms += " madness_weaving:2"
    line = (
        f"Solved loadout voidform misery ancient_madness distorted_reality death_and_madness voidtouched {idols} {bottoms} 21112 profileset.\"VF\"+=\"X\"\n"
    )
    with open(profile, "w", encoding="utf8") as f:
        f.write(line)

    ttm.convert_builds(str(profile))
    with open(profile, "r", encoding="utf8") as f:
        out = f.read()
    # expect the generated suffix and idols to be present
    assert "_Mis" in out and "_AM" in out and "_DR" in out and "_DaM" in out and "_VT" in out
    assert 'profileset."VF_yshaarj_nzoth_yogg' in out


def test_single_and_no_idol_behavior(tmp_path, monkeypatch):
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    monkeypatch.chdir(os.path.join(root, "talents"))
    ttm = load_ttm_module(root)

    # single idol -> lines with <=2 idols are NOT added by convert_builds
    profile1 = tmp_path / "single.simc"
    line1 = (
        "Solved loadout voidform idol_of_yogg "
        + "mindbender:1 deathspeaker:1 death_and_madness:1 mind_devourer:1 auspicious_spirits:1 inescapable_torment:1 deaths_torment:1 screams_of_the_void:1 madness_weaving:2 22111 "
        + 'profileset."VF"+="S"\n'
    )
    with open(profile1, "w", encoding="utf8") as f:
        f.write(line1)
    ttm.convert_builds(str(profile1))
    with open(profile1, "r", encoding="utf8") as f:
        _ = f.read()
    # single idol -> should now be included (idols suffix appended)
    # assert 'profileset."VF_yogg' in out1

    # no idol -> also filtered because IDOLS_COUNT <= 2
    profile2 = tmp_path / "none.simc"
    line2 = (
        "Solved loadout voidform "
        + "mindbender:1 deathspeaker:1 death_and_madness:1 mind_devourer:1 auspicious_spirits:1 inescapable_torment:1 deaths_torment:1 screams_of_the_void:1 madness_weaving:2 22111 "
        + 'profileset."VF"+="S"\n'
    )
    with open(profile2, "w", encoding="utf8") as f:
        f.write(line2)
    ttm.convert_builds(str(profile2))
    with open(profile2, "r", encoding="utf8") as f:
        out2 = f.read()
    assert out2.strip() == "# Automatically generated by ttm.py"


def test_apply_rules_filters_after_replacement(tmp_path, monkeypatch):
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    monkeypatch.chdir(os.path.join(root, "talents"))
    ttm = load_ttm_module(root)

    profile = tmp_path / "filtered.simc"
    # includes tormented_spirits without idol_of_yoggsaron -> should be filtered out
    line = "Solved loadout no_void tormented_spirits mindbender:2 deathspeaker:2 death_and_madness:2 mind_devourer:2 auspicious_spirits:2 inescapable_torment:2 deaths_torment:2 screams_of_the_void:2 22111 profileset.\"NOCD\"+=\"S\"\n"
    with open(profile, "w", encoding="utf8") as f:
        f.write(line)
    ttm.convert_builds(str(profile))
    with open(profile, "r", encoding="utf8") as f:
        out = f.read()
    # only signature should remain because the line was filtered
    assert out.strip() == "# Automatically generated by ttm.py"


def test_runtime_registration_and_restore():
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    ttm = load_ttm_module(root)
    # save originals
    orig_pairs = list(ttm.CHOICE_NODE_PAIRS)
    orig_singletons = list(ttm.CHOICE_NODE_SINGLETONS)
    orig_idols = list(ttm.IDOLS)
    try:
        # register new entries
        ttm.register_choice_pair(("alpha", "beta"), ("A", "B"))
        ttm.register_choice_singleton("gamma", "G")
        ttm.register_idol("test_idol")
        assert (("alpha", "beta"), ("A", "B")) in ttm.CHOICE_NODE_PAIRS
        assert ("gamma", "G") in ttm.CHOICE_NODE_SINGLETONS
        assert "test_idol" in ttm.IDOLS
    finally:
        # restore originals to avoid cross-test pollution
        ttm.CHOICE_NODE_PAIRS[:] = orig_pairs
        ttm.CHOICE_NODE_SINGLETONS[:] = orig_singletons
        ttm.IDOLS[:] = orig_idols


def test_load_config_applies_talents_section(tmp_path):
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    ttm = load_ttm_module(root)
    # prepare a temp config with a talents section
    cfg = {
        "talents": {
            "choice_pairs": [
                {"keywords": ["foo", "bar"], "suffixes": ["F", "B"]}
            ],
            "choice_singletons": [{"keyword": "baz", "suffix": "Z"}],
            "idols": ["cfg_idol"],
        }
    }
    cfg_path = tmp_path / "cfg.yml"
    import yaml as _yaml

    cfg_path.write_text(_yaml.dump(cfg), encoding="utf8")

    # save originals
    orig_pairs = list(ttm.CHOICE_NODE_PAIRS)
    orig_singletons = list(ttm.CHOICE_NODE_SINGLETONS)
    orig_idols = list(ttm.IDOLS)
    try:
        # load config from the temporary file (should apply talents section)
        ttm.load_config(str(cfg_path))
        assert (("foo", "bar"), ("F", "B")) in ttm.CHOICE_NODE_PAIRS
        assert ("baz", "Z") in ttm.CHOICE_NODE_SINGLETONS
        assert "cfg_idol" in ttm.IDOLS
    finally:
        # restore
        ttm.CHOICE_NODE_PAIRS[:] = orig_pairs
        ttm.CHOICE_NODE_SINGLETONS[:] = orig_singletons
        ttm.IDOLS[:] = orig_idols
        ttm.config = None
